sudo: false
language: elixir
elixir:
  - 1.2.0
otp_release:
  - 18.2.1
install: "true"
branches:
  only:
    - master
script: "make test dialyzer"
cache:
  directories:
  - _plt
  - $HOME/.mix/archives
notifications:
  email:
    - priestjim@gmail.com
